// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicMate.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MusicMate.Infrastructure.Migrations
{
    [DbContext(typeof(MusicMateDbContext))]
    partial class MusicMateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MusicMate.Domain.Entities.Matching", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("first_user_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("matched_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("second_user_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("first_user_id");

                    b.HasIndex("second_user_id");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("MusicMate.Domain.Entities.Message", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("receiver_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("sender_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("receiver_id");

                    b.HasIndex("sender_id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MusicMate.Domain.Entities.MusicGenre", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("MusicGenres");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "Pop"
                        },
                        new
                        {
                            id = 2,
                            name = "Rock"
                        },
                        new
                        {
                            id = 3,
                            name = "Hip-Hop"
                        },
                        new
                        {
                            id = 4,
                            name = "Ballad"
                        },
                        new
                        {
                            id = 5,
                            name = "R&B"
                        },
                        new
                        {
                            id = 6,
                            name = "Indie"
                        },
                        new
                        {
                            id = 7,
                            name = "Jazz"
                        },
                        new
                        {
                            id = 8,
                            name = "EDM"
                        });
                });

            modelBuilder.Entity("MusicMate.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("bio")
                        .HasColumnType("text");

                    b.Property<string>("city")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("display_name")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("hashed_password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("user_avatar")
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MusicMate.Domain.Entities.UserFavoriteGenre", b =>
                {
                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.Property<int>("genre_id")
                        .HasColumnType("integer");

                    b.HasKey("user_id", "genre_id");

                    b.HasIndex("genre_id");

                    b.ToTable("UserFavoriteGenres");
                });

            modelBuilder.Entity("MusicMate.Domain.Entities.Matching", b =>
                {
                    b.HasOne("MusicMate.Domain.Entities.User", "first_user")
                        .WithMany("matches_at_first")
                        .HasForeignKey("first_user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MusicMate.Domain.Entities.User", "second_user")
                        .WithMany("matches_at_second")
                        .HasForeignKey("second_user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("first_user");

                    b.Navigation("second_user");
                });

            modelBuilder.Entity("MusicMate.Domain.Entities.Message", b =>
                {
                    b.HasOne("MusicMate.Domain.Entities.User", "receiver")
                        .WithMany("received_messages")
                        .HasForeignKey("receiver_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MusicMate.Domain.Entities.User", "sender")
                        .WithMany("sent_messages")
                        .HasForeignKey("sender_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("receiver");

                    b.Navigation("sender");
                });

            modelBuilder.Entity("MusicMate.Domain.Entities.UserFavoriteGenre", b =>
                {
                    b.HasOne("MusicMate.Domain.Entities.MusicGenre", "genre")
                        .WithMany("users")
                        .HasForeignKey("genre_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicMate.Domain.Entities.User", "user")
                        .WithMany("favorite_genres")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("genre");

                    b.Navigation("user");
                });

            modelBuilder.Entity("MusicMate.Domain.Entities.MusicGenre", b =>
                {
                    b.Navigation("users");
                });

            modelBuilder.Entity("MusicMate.Domain.Entities.User", b =>
                {
                    b.Navigation("favorite_genres");

                    b.Navigation("matches_at_first");

                    b.Navigation("matches_at_second");

                    b.Navigation("received_messages");

                    b.Navigation("sent_messages");
                });
#pragma warning restore 612, 618
        }
    }
}
